module.exports = {
        unauthorized: "unauthorized",
        exists: "already exists",
        categoryId: "invalid categoryId",
        brandId: "invalid brandId",
        productId: "invalid productId",
        invalidToken: "invalid token",
        internalServerError: "internal Server Error",
        success: "success",
        list: "unable to fetch",
        created: "created successfully",
        create: "unable to create",
        updated: "updated successfully",
        update: "unable to update",
        deleted: "deleted successfully",
        delete: "unable to delete",
        false: "false",
        true: "true",
        notFound: "not found",
        duplicate: "duplicate entry",
        badRequest: "bad request",
        role: "invalid role",
        tokenMissing: "authorization header missing or invalid",
        incorrect: "invalid email or password",
        password: "invalid password",
        email: "invalid email",
        invalidStart: "invalid rent start date",
        invalidEnd: "Invalid rent end date",
        product: "invalid product ID",
        user: "invalid user ID",
        quantity: "invalid quantity",
        booked: "product is already booked for the selected dates",
        notAvailable: "Product is not available for sale",
        invalidRent: "Product is not available for rent",
        records: "no records found",
        date: "Rent date cannot be in the past",
        fetch_products: "An error occurred while fetching products.",
        fetch_orders: "An error occurred while fetching orders.",
        Unable_To_fetch_users: "An error occurred while fetching users.",
        Unable_To_fetch_items: "An error occurred while fetching items.",
        Unable_To_Update_users: "An error occurred while updating users.",
        Unable_To_Update_Items: "An error occurred while updating items.",
        Unable_To_Fetch_Orders: "An error occurred while fetching orders.",
        Unable_To_Delete_Orders: "An error occurred while deleting orders.",
        Unable_To_Delete_Products: "An error occurred while deleting products.",
        Unable_To_Fetch_MasterData: "An error occurred while fetching masterData.",
        Not_Found: "Not Found",
        Correct_Page_Limit: "provide correct page and limit",
        Successfully_deleted: "Order deleted successfully",
        Product_deleted: "Product deleted successfully",
        Unable_To_Swap_Categories: "Unable_To_Swap_Categories",
        User_Already_Exists: "User_Already_Exists",
        id: 'invalid id',
};